/** Code-owned public marketing routes that do not depend on admin website configuration. */
export const STATIC_MARKETING_PATHS = [
  "/",
  "/care",
  "/caregivers",
  "/start",
  "/product",
  "/for-pet-owners",
  "/for-providers",
  "/service-flow",
  "/rewards",
  "/payments",
  "/trust",
  "/stories",
  "/help",
  "/miniapp",
  "/about",
  "/contact",
  "/terms",
  "/privacy",
  "/refund-policy",
  "/platform-rules",
] as const;
