/** Miniapp shared visual tokens. Keep reusable values here instead of page class literals. */
export const miniappDesignTokens = {
  colors: {
    canvas: "#f8fafc",
    "page-bg": "#f6f7fb",
    surface: "#ffffff",
    ink: "#1f2937",
    muted: "#667085",
    subtle: "#98a2b3",
    brand: "#4a6cf7",
    "brand-active": "#3552c8",
    soft: "#eef2ff",
    border: "#eaecf0",
    divider: "#f2f4f7",
    success: "#12b76a",
    "success-soft": "#ecfdf3",
    warning: "#f79009",
    "warning-soft": "#fffaeb",
    danger: "#f04438",
    "danger-soft": "#fef3f2",
  },
  spacing: {
    xxs: "2px",
    caption: "4px",
    compact: "6px",
    "surface-overlap": "8px",
    sm: "8px",
    copy: "12px",
    action: "16px",
    "page-horizontal": "16px",
    "navigation-horizontal": "16px",
    "card-padding": "16px",
    card: "20px",
    screen: "24px",
    "section-gap": "24px",
    section: "32px",
    actions: "64px",
    statement: "68px",
    "hero-bleed": "-15px",
  },
  sizes: {
    dot: "6px",
    progress: "6px",
    "icon-xs": "16px",
    "icon-sm": "20px",
    "icon-md": "32px",
    "avatar-sm": "36px",
    avatar: "44px",
    "avatar-lg": "56px",
    "tab-indicator": "3px",
    "mini-cover": "64px",
    pet: "72px",
    "card-cover": "104px",
    indicator: "20px",
    "feed-card": "264px",
    control: "44px",
    header: "48px",
    tabbar: "52px",
    "safe-area-max": "48px",
    fab: "52px",
    segment: "36px",
    "hero-main": "176px",
    hero: "240px",
    "hero-image": "530px",
    "hero-copy": "54%",
    "logo-width": "99px",
    "logo-height": "78px",
    commitments: "72px",
    icon: "40px",
    glyph: "24px",
    agreement: "280px",
    button: "52px",
  },
  radii: {
    badge: "6px",
    chip: "8px",
    card: "16px",
    surface: "24px",
    control: "12px",
    pill: "999px",
  },
  fontSizes: {
    micro: "11px",
    small: "13px",
    title: "24px",
    page: "22px",
    section: "18px",
    card: "16px",
    tab: "15px",
    amount: "20px",
    body: "14px",
    caption: "12px",
    button: "16px",
  },
  lineHeights: {
    badge: "16px",
    micro: "16px",
    small: "20px",
    title: "32px",
    page: "30px",
    section: "26px",
    card: "24px",
    body: "22px",
    label: "20px",
    caption: "18px",
    button: "24px",
  },
  shadows: {
    card: "0 2px 12px rgba(16, 24, 40, 0.06)",
    float: "0 8px 24px rgba(74, 108, 247, 0.28)",
  },
} as const;
