/** RBAC permission categories supported by the shared catalog. */
export const RBAC_PERMISSION_TYPES = {
  MENU: "menu",
  BUTTON: "button",
  API: "api",
} as const;

/** A permission category declared by the RBAC catalog. */
export type RbacPermissionType = (typeof RBAC_PERMISSION_TYPES)[keyof typeof RBAC_PERMISSION_TYPES];

/** A code-defined permission available to the administration system. */
export interface RbacPermissionDefinition {
  /** Stable authorization code stored in role assignments. */
  code: string;
  /** Whether the permission represents a menu, button, or server API. */
  type: RbacPermissionType;
  /** Human-readable permission name for administrative users. */
  label: string;
  /** Business module that owns the permission. */
  module: string;
  /** Administration route for menu permissions, otherwise null. */
  path: string | null;
  /** Parent menu code for nested menus and buttons, otherwise null. */
  parentCode: string | null;
  /** Stable display order within the parent menu. */
  order: number;
  /** Icon identifier for menu permissions, otherwise null. */
  icon: string | null;
  /** API permissions granted automatically with this UI permission. */
  impliedApiCodes: readonly string[];
}

/** The complete, code-defined RBAC permission catalog. */
export const RBAC_PERMISSION_CATALOG: readonly RbacPermissionDefinition[] = [
  {
    code: "stats.view",
    type: "menu",
    label: "运营概览",
    module: "stats",
    path: "/",
    parentCode: null,
    order: 10,
    icon: "House",
    impliedApiCodes: ["stats.dashboard"],
  },
  {
    code: "stats.dashboard",
    type: "api",
    label: "查看运营数据",
    module: "stats",
    path: null,
    parentCode: null,
    order: 10,
    icon: null,
    impliedApiCodes: [],
  },
  {
    code: "user.view",
    type: "menu",
    label: "用户管理",
    module: "user",
    path: "/users",
    parentCode: null,
    order: 20,
    icon: "Users",
    impliedApiCodes: ["user.read"],
  },
  {
    code: "user.read",
    type: "api",
    label: "查看用户列表",
    module: "user",
    path: null,
    parentCode: null,
    order: 10,
    icon: null,
    impliedApiCodes: [],
  },
  {
    code: "user.create",
    type: "api",
    label: "创建用户",
    module: "user",
    path: null,
    parentCode: null,
    order: 20,
    icon: null,
    impliedApiCodes: [],
  },
  {
    code: "user.update",
    type: "api",
    label: "更新用户",
    module: "user",
    path: null,
    parentCode: null,
    order: 30,
    icon: null,
    impliedApiCodes: [],
  },
  {
    code: "user.delete",
    type: "api",
    label: "删除用户",
    module: "user",
    path: null,
    parentCode: null,
    order: 40,
    icon: null,
    impliedApiCodes: [],
  },
  {
    code: "user.approve_provider",
    type: "button",
    label: "审核服务提供者",
    module: "user",
    path: null,
    parentCode: "user.view",
    order: 10,
    icon: null,
    impliedApiCodes: ["provider_certification.approve"],
  },
  {
    code: "user.reject_provider",
    type: "button",
    label: "驳回服务提供者",
    module: "user",
    path: null,
    parentCode: "user.view",
    order: 20,
    icon: null,
    impliedApiCodes: ["provider_certification.reject"],
  },
  {
    code: "provider_certification.view",
    type: "menu",
    label: "认证审核",
    module: "provider_certification",
    path: "/users/certifications",
    parentCode: "user.view",
    order: 30,
    icon: "BadgeCheck",
    impliedApiCodes: ["provider_certification.read"],
  },
  {
    code: "provider_certification.read",
    type: "api",
    label: "查看认证申请",
    module: "provider_certification",
    path: null,
    parentCode: null,
    order: 10,
    icon: null,
    impliedApiCodes: [],
  },
  {
    code: "provider_certification.approve",
    type: "api",
    label: "通过认证申请",
    module: "provider_certification",
    path: null,
    parentCode: null,
    order: 20,
    icon: null,
    impliedApiCodes: [],
  },
  {
    code: "provider_certification.reject",
    type: "api",
    label: "驳回认证申请",
    module: "provider_certification",
    path: null,
    parentCode: null,
    order: 30,
    icon: null,
    impliedApiCodes: [],
  },
  {
    code: "order.view",
    type: "menu",
    label: "订单管理",
    module: "order",
    path: "/orders",
    parentCode: null,
    order: 30,
    icon: "ShoppingBag",
    impliedApiCodes: ["order.read"],
  },
  {
    code: "order.read",
    type: "api",
    label: "查看订单列表",
    module: "order",
    path: null,
    parentCode: null,
    order: 10,
    icon: null,
    impliedApiCodes: [],
  },
  {
    code: "order.create",
    type: "api",
    label: "创建订单",
    module: "order",
    path: null,
    parentCode: null,
    order: 20,
    icon: null,
    impliedApiCodes: [],
  },
  {
    code: "order.update",
    type: "api",
    label: "更新订单",
    module: "order",
    path: null,
    parentCode: null,
    order: 30,
    icon: null,
    impliedApiCodes: [],
  },
  {
    code: "order.cancel",
    type: "button",
    label: "取消订单",
    module: "order",
    path: null,
    parentCode: "order.view",
    order: 10,
    icon: null,
    impliedApiCodes: ["order.update"],
  },
  {
    code: "order.export",
    type: "button",
    label: "导出订单数据",
    module: "order",
    path: null,
    parentCode: "order.view",
    order: 20,
    icon: null,
    impliedApiCodes: ["order.export_data"],
  },
  {
    code: "order.export_data",
    type: "api",
    label: "导出订单数据接口",
    module: "order",
    path: null,
    parentCode: null,
    order: 40,
    icon: null,
    impliedApiCodes: [],
  },
  {
    code: "dispute.view",
    type: "menu",
    label: "投诉与纠纷",
    module: "dispute",
    path: "/orders/complaints",
    parentCode: "order.view",
    order: 30,
    icon: "MessageSquareWarning",
    impliedApiCodes: ["dispute.read"],
  },
  {
    code: "dispute.read",
    type: "api",
    label: "查看投诉列表",
    module: "dispute",
    path: null,
    parentCode: null,
    order: 10,
    icon: null,
    impliedApiCodes: [],
  },
  {
    code: "dispute.resolve",
    type: "button",
    label: "处理投诉纠纷",
    module: "dispute",
    path: null,
    parentCode: "dispute.view",
    order: 10,
    icon: null,
    impliedApiCodes: ["dispute.resolve_action"],
  },
  {
    code: "dispute.resolve_action",
    type: "api",
    label: "处理投诉纠纷接口",
    module: "dispute",
    path: null,
    parentCode: null,
    order: 20,
    icon: null,
    impliedApiCodes: [],
  },
  {
    code: "system.view",
    type: "menu",
    label: "系统设置",
    module: "system",
    path: "/settings",
    parentCode: null,
    order: 60,
    icon: "Settings",
    impliedApiCodes: ["system.read"],
  },
  {
    code: "system.read",
    type: "api",
    label: "查看系统设置",
    module: "system",
    path: null,
    parentCode: null,
    order: 10,
    icon: null,
    impliedApiCodes: [],
  },
  {
    code: "system.config",
    type: "button",
    label: "系统配置",
    module: "system",
    path: null,
    parentCode: "system.view",
    order: 10,
    icon: null,
    impliedApiCodes: ["system.config_action"],
  },
  {
    code: "system.config_action",
    type: "api",
    label: "系统配置接口",
    module: "system",
    path: null,
    parentCode: null,
    order: 20,
    icon: null,
    impliedApiCodes: [],
  },
  {
    code: "system.sop_config",
    type: "button",
    label: "SOP 配置",
    module: "system",
    path: null,
    parentCode: "system.view",
    order: 20,
    icon: null,
    impliedApiCodes: ["system.sop_config_action"],
  },
  {
    code: "system.sop_config_action",
    type: "api",
    label: "SOP 配置接口",
    module: "system",
    path: null,
    parentCode: null,
    order: 30,
    icon: null,
    impliedApiCodes: [],
  },
  {
    code: "system.threshold_config",
    type: "button",
    label: "评分阈值配置",
    module: "system",
    path: null,
    parentCode: "system.view",
    order: 30,
    icon: null,
    impliedApiCodes: ["system.threshold_config_action"],
  },
  {
    code: "system.threshold_config_action",
    type: "api",
    label: "评分阈值配置接口",
    module: "system",
    path: null,
    parentCode: null,
    order: 40,
    icon: null,
    impliedApiCodes: [],
  },
  {
    code: "system.fee_config",
    type: "button",
    label: "费率配置",
    module: "system",
    path: null,
    parentCode: "system.view",
    order: 40,
    icon: null,
    impliedApiCodes: ["system.fee_config_action"],
  },
  {
    code: "system.fee_config_action",
    type: "api",
    label: "费率配置接口",
    module: "system",
    path: null,
    parentCode: null,
    order: 50,
    icon: null,
    impliedApiCodes: [],
  },
  {
    code: "system.publish",
    type: "button",
    label: "发布系统设置",
    module: "system",
    path: null,
    parentCode: "system.view",
    order: 50,
    icon: null,
    impliedApiCodes: ["system.publish_action"],
  },
  {
    code: "system.publish_action",
    type: "api",
    label: "发布系统设置接口",
    module: "system",
    path: null,
    parentCode: null,
    order: 60,
    icon: null,
    impliedApiCodes: [],
  },
  {
    code: "rbac.view",
    type: "menu",
    label: "权限管理",
    module: "rbac",
    path: "/rbac",
    parentCode: "system.view",
    order: 60,
    icon: "ShieldCheck",
    impliedApiCodes: ["rbac.permission.read", "rbac.role.read"],
  },
  {
    code: "rbac.role.read",
    type: "api",
    label: "查看角色列表",
    module: "rbac",
    path: null,
    parentCode: null,
    order: 10,
    icon: null,
    impliedApiCodes: [],
  },
  {
    code: "rbac.role.create",
    type: "button",
    label: "创建角色",
    module: "rbac",
    path: null,
    parentCode: "rbac.view",
    order: 10,
    icon: null,
    impliedApiCodes: ["rbac.role.create_action"],
  },
  {
    code: "rbac.role.create_action",
    type: "api",
    label: "创建角色接口",
    module: "rbac",
    path: null,
    parentCode: null,
    order: 20,
    icon: null,
    impliedApiCodes: [],
  },
  {
    code: "rbac.role.update",
    type: "button",
    label: "更新角色",
    module: "rbac",
    path: null,
    parentCode: "rbac.view",
    order: 20,
    icon: null,
    impliedApiCodes: ["rbac.role.update_action"],
  },
  {
    code: "rbac.role.update_action",
    type: "api",
    label: "更新角色接口",
    module: "rbac",
    path: null,
    parentCode: null,
    order: 30,
    icon: null,
    impliedApiCodes: [],
  },
  {
    code: "rbac.role.delete",
    type: "button",
    label: "删除角色",
    module: "rbac",
    path: null,
    parentCode: "rbac.view",
    order: 30,
    icon: null,
    impliedApiCodes: ["rbac.role.delete_action"],
  },
  {
    code: "rbac.role.delete_action",
    type: "api",
    label: "删除角色接口",
    module: "rbac",
    path: null,
    parentCode: null,
    order: 40,
    icon: null,
    impliedApiCodes: [],
  },
  {
    code: "rbac.permission.read",
    type: "api",
    label: "查看权限点",
    module: "rbac",
    path: null,
    parentCode: null,
    order: 50,
    icon: null,
    impliedApiCodes: [],
  },
  {
    code: "rbac.assign_role",
    type: "button",
    label: "分配用户角色",
    module: "rbac",
    path: null,
    parentCode: "rbac.view",
    order: 40,
    icon: null,
    impliedApiCodes: ["rbac.assign_role_action"],
  },
  {
    code: "rbac.assign_role_action",
    type: "api",
    label: "分配用户角色接口",
    module: "rbac",
    path: null,
    parentCode: null,
    order: 60,
    icon: null,
    impliedApiCodes: [],
  },
];

/** Looks up a catalog permission by its stable authorization code. */
export function getRbacPermission(code: string): RbacPermissionDefinition | undefined {
  return RBAC_PERMISSION_CATALOG.find((permission) => permission.code === code);
}

/** Returns the current catalog version identifier. */
export function getRbacCatalogVersion(): string {
  return "2026-08-02";
}

/** Returns the menu and button codes that role editors may assign. */
export function getRbacUiPermissionCodes(): readonly string[] {
  return RBAC_PERMISSION_CATALOG.filter(
    (permission) => permission.type !== RBAC_PERMISSION_TYPES.API,
  ).map((permission) => permission.code);
}
