packages:
  - "apps/*"
  - "packages/*"

pmOnFail: download
engineStrict: true
nodeVersion: "24.19.0"
saveExact: true

allowBuilds:
  "@alicloud/openapi-core": false
  "@parcel/watcher": true
  "@prisma/engines": true
  "@scarf/scarf": false
  "@swc/core": true
  "@uni-helper/unocss-preset-uni": true
  argon2: true
  core-js: false
  core-js-pure: false
  esbuild: true
  less: true
  msgpackr-extract: true
  prisma: true
  protobufjs: true
  unrs-resolver: true
  vue-demi: true

packageExtensions:
  "@dcloudio/uni-cli-shared@3.0.0-4080520251106001":
    dependencies:
      postcss: "8.4.45"
  "@dcloudio/uni-h5-vite@3.0.0-4080520251106001":
    dependencies:
      vite: "5.4.21"
  "@wot-ui/ui@2.3.1":
    peerDependencies:
      "@dcloudio/uni-app": "3.0.0-4080520251106001"
