/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    MainTabLayout: typeof import('./components/MainTabLayout.vue')['default']
    SubPageLayout: typeof import('./components/SubPageLayout.vue')['default']
    WdButton: typeof import('@wot-ui/ui/components/wd-button/wd-button.vue')['default']
    WdTabbar: typeof import('@wot-ui/ui/components/wd-tabbar/wd-tabbar.vue')['default']
    WdTabbarItem: typeof import('@wot-ui/ui/components/wd-tabbar-item/wd-tabbar-item.vue')['default']
  }
}
