/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/index/index" |
  "/pages/auth/index" |
  "/pages/community/index" |
  "/pages/messages/index" |
  "/pages/profile/index" |
  "/pages-account/pets/index" |
  "/pages-account/pets/form" |
  "/pages-account/pets/detail" |
  "/pages-account/profile/info" |
  "/pages-account/profile/edit" |
  "/pages-account/account/cancel" |
  "/pages-content/classroom/article" |
  "/pages-content/community/article" |
  "/pages-content/community/publish" |
  "/pages-content/help/index" |
  "/pages-content/contact/index" |
  "/pages-content/legal/index";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
  export type LocationUrl = _LocationUrl;
}
