/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/index/index" |
  "/pages/auth/index" |
  "/pages/bounty/index" |
  "/pages/community/index" |
  "/pages/messages/index" |
  "/pages/profile/index" |
  "/pages-bounty/publish/step1" |
  "/pages-bounty/publish/step2" |
  "/pages-bounty/publish/step3" |
  "/pages-bounty/publish/success" |
  "/pages-bounty/reward/detail" |
  "/pages-care/orders/index" |
  "/pages-care/order/detail" |
  "/pages-care/monitor/index" |
  "/pages-care/chat/index" |
  "/pages-account/pets/index" |
  "/pages-account/pets/form" |
  "/pages-account/pets/detail" |
  "/pages-account/favorites/index" |
  "/pages-account/follows/index" |
  "/pages-account/reviews/index" |
  "/pages-account/services/detail" |
  "/pages-account/caregivers/detail" |
  "/pages-account/stores/detail" |
  "/pages-account/creators/detail" |
  "/pages-account/profile/info" |
  "/pages-account/profile/edit" |
  "/pages-account/account/cancel" |
  "/pages-content/classroom/article" |
  "/pages-content/community/article" |
  "/pages-content/community/publish" |
  "/pages-content/coupons/index" |
  "/pages-content/wallet/index" |
  "/pages-content/help/index" |
  "/pages-content/contact/index" |
  "/pages-content/legal/index";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
  export type LocationUrl = _LocationUrl;
}
