import { describe, expect, it } from "vitest";
import pagesConfig, { createMiniappPagesConfig, removeGeneratedSubPackage } from "./pages.config";

const expectedSubPages = [
  "pages-account/pets/index",
  "pages-account/pets/form",
  "pages-account/pets/detail",
  "pages-account/profile/info",
  "pages-account/profile/edit",
  "pages-account/account/settings",
  "pages-account/account/cancel",
  "pages-content/classroom/article",
  "pages-content/community/article",
  "pages-content/community/publish",
  "pages-content/help/index",
  "pages-content/contact/index",
  "pages-content/legal/index",
] as const;

describe("miniapp page contract", () => {
  it("does not reserve a native tab bar behind the custom root layout", () => {
    expect(pagesConfig.tabBar).toBeUndefined();
  });

  it("registers all subpackage pages exactly once", () => {
    const actual = (pagesConfig.subPackages ?? []).flatMap(({ root, pages }) =>
      pages.map(({ path }) => `${root}/${path}`),
    );

    expect(actual).toEqual(expectedSubPages);
    expect(new Set(actual).size).toBe(expectedSubPages.length);
  });

  it("does not register commercial route groups in the default build", () => {
    const registered = JSON.stringify(pagesConfig.subPackages ?? []);

    expect(registered).not.toContain("pages-bounty");
    expect(registered).not.toContain("pages-care");
    expect(registered).not.toContain("wallet");
    expect(registered).not.toContain("coupons");
  });

  it("registers only the Cycle 5 bounty pages when the build explicitly enables them", () => {
    const enabled = createMiniappPagesConfig(true);
    const registered = (enabled.subPackages ?? []).flatMap(({ root, pages }) =>
      pages.map(({ path }) => `${root}/${path}`),
    );

    expect(registered).toContain("pages-bounty/index");
    expect(registered).toContain("pages-bounty/form");
    expect(registered).not.toContain("pages-care");
    expect(registered).not.toContain("wallet");
  });

  it("removes a stale generated bounty package without corrupting neighboring routes", () => {
    const source = `{
  "subPackages": [
    {
      "root": "pages-account",
      "pages": []
    },
    {
      "root": "pages-bounty",
      "pages": [
        // GENERATED BY UNI-PAGES
        { "path": "index", "style": { "navigationStyle": "custom" } }
      ]
    }
  ]
}`;
    const cleaned = removeGeneratedSubPackage(source, "pages-bounty");

    expect(cleaned).not.toContain("pages-bounty");
    expect(JSON.parse(cleaned)).toEqual({
      subPackages: [{ root: "pages-account", pages: [] }],
    });
    expect(removeGeneratedSubPackage(cleaned, "pages-bounty")).toBe(cleaned);
  });
});
